export default {
    base:{
        type:'not assigned',
        name:'not assigned',
        enemy:false,
        class:'not assigned',
        lvl:1,
        exp:0,
        live:false,
        exp_boost:1,
        gold_boost:1,
        mineral_boost:1,
        drop_boost:1,
        max_hp:10,
        current_hp:5,
        regeration_hp:0.2,
        max_mp:5,
        current_mp:2,
        regeration_hp:0.1,
        phisic_def:0,
        magic_def:0,
        phisic_attak:1,
        magic_attak:1,
        phisic_attak_spd:10,
        magic_attak_spd:10,
        crit_chance:1,
        crit_rate:1.1,
        accuracy:10,
        evasion:10,
        fire_resistance:0,
        woter_resistance:0,
        wind_resistance:0,
        earth_resistance:0,
        holy_resistance:0,
        dark_resistance:0,
        fire_wekness:0,
        woter_wekness:0,
        wind_wekness:0,
        earth_wekness:0,
        holy_wekness:0,
        dark_wekness:0,
        dropList:'not assigned',
        inventory:'not assigned',
        activeInventoryPlayer:'not assigned',
        spell:'not assigned',
        skill :'not assigned'
    },
    player:{},
    monsters:{}
}